-- 1A
CREATE TABLE A6_LRS (
    GEOM SDO_GEOMETRY
);

-- 1B
INSERT INTO 
    A6_LRS 
SELECT 
    S.GEOM 
FROM 
    STREETS_AND_RAILROADS S,
    MAJOR_CITIES C
WHERE 
    SDO_RELATE(S.geom, SDO_GEOM.SDO_BUFFER(C.geom, 10, 1, 'unit=km'), 'MASK=ANYINTERACT') = 'TRUE' 
AND 
    C.city_name = 'Koszalin';

-- 1C
SELECT 
    SDO_GEOM.SDO_LENGTH(A.GEOM, 1, 'unit=km') DISTANCE,
    ST_LINESTRING(A.GEOM).ST_NUMPOINTS() NUMPOINTS
FROM 
    A6_LRS A;

-- 1D
UPDATE A6_LRS A SET 
    A.GEOM = SDO_LRS.CONVERT_TO_LRS_GEOM(A.geom, 0, SDO_LRS.GEOM_SEGMENT_LENGTH(A.geom));

-- 1E
INSERT INTO USER_SDO_GEOM_METADATA VALUES (
    'A6_LRS', 
    'GEOM', 
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1), 
        SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
        SDO_DIM_ELEMENT('M', 0, 300, 1)
    ), 
    8307
);

-- 1F
CREATE INDEX A6_LRS_IDX ON A6_LRS(GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- 2A
SELECT 
SDO_LRS.VALID_MEASURE(GEOM, 500) VALID_500
FROM A6_LRS;

-- 2B 
SELECT 
SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) END_PT
FROM A6_LRS;

-- 2C
SELECT 
SDO_LRS.LOCATE_PT(GEOM, 150) KM150
FROM A6_LRS;

-- 2D
SELECT 
SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) CLIPPED
FROM A6_LRS;

-- 2E
SELECT 
SDO_LRS.GET_NEXT_SHAPE_PT(A.geom, SDO_LRS.PROJECT_PT(A.geom, C.geom)) WJAZD_NA_A6
FROM A6_LRS A, MAJOR_CITIES C 
WHERE C.CITY_NAME = 'Slupsk';

-- 2F
SELECT 
SDO_GEOM.SDO_LENGTH(
    SDO_LRS.OFFSET_GEOM_SEGMENT(A6.GEOM, M.DIMINFO, 50000, 200000, 50, 'unit=m arc_tolerance=1'),
    1, 'unit=km'
) KOSZT
from A6_LRS A6, USER_SDO_GEOM_METADATA M
where M.TABLE_NAME = 'A6_LRS' and M.COLUMN_NAME = 'GEOM';